Update 9vKqVkMQHKk.sbv
romankoshlyak/neural_networks_translation pull request #3
Opened 2020-07-17 10:53 UTC by OlZas

звукова доріжка значною мірою відрізняється від оригінальних субтитрів

2020-07-17 17:18 UTC, romankoshlyak requested changes

2020-07-17 17:18 UTC, romankoshlyak commented on 9vKqVkMQHKk.sbv
> +влучним математичним терміном: похідна.
формальної матиматики
правильної математики
тут змінюється смисл якщо сказати терміном, вони кмітливі були не тому що термін придумати

2020-07-17 17:18 UTC, romankoshlyak commented on 9vKqVkMQHKk.sbv
> +зростає, що відповідає більш крутому підйому на графіку.
нахил буде краще

2020-07-17 17:18 UTC, romankoshlyak commented on 9vKqVkMQHKk.sbv
> +
видаляй пусті

2020-07-17 17:18 UTC, romankoshlyak commented on 9vKqVkMQHKk.sbv
> +
видаляй, краще  змінюй кінцевий час попередьного на кінцевий час видаленого

2020-07-17 17:18 UTC, romankoshlyak commented on 9vKqVkMQHKk.sbv
> +Наприклад, істинна, чиста математична похідна функції s (t) записується як ds/dt,
s (t) -> s(t)

2020-07-17 19:02 UTC, romankoshlyak requested changes

2020-07-17 19:02 UTC, romankoshlyak commented on 9vKqVkMQHKk.sbv
> +зробило б обчислення набагато складнішим, але, як не дивно, це насправді
зробило б, та полегшує, різні часи

2020-07-17 19:02 UTC, romankoshlyak commented on 9vKqVkMQHKk.sbv
> +Оскільки s (t) = t3, то цей чисельник дорівнює (2 + dt)3 - 2х2х2.
s (t) -> s(t)

2020-07-17 19:02 UTC, romankoshlyak commented on 9vKqVkMQHKk.sbv
> +Оскільки s (t) = t3, то цей чисельник дорівнює (2 + dt)3 - 2х2х2.
t3 -> t^3

2020-07-17 19:02 UTC, romankoshlyak commented on 9vKqVkMQHKk.sbv
> +Коли ви робите розрахунки в числівнику, ви отримуєте 23 + 3 * 22dt + 3 * 2 * (dt) 2
2^3+3*2^2*dt + 3*2*dt^2+dt^3

2020-07-17 19:02 UTC, romankoshlyak commented on 9vKqVkMQHKk.sbv
> +Ці числа 2х2х2 спрощуються.
2^3

2020-07-17 19:02 UTC, romankoshlyak commented on 9vKqVkMQHKk.sbv
> +Це означає, що відношення ds/dt спростилося до 3 * 22 + два різні числа, кожне з яких містить dt
3*2^2

2020-07-17 19:02 UTC, romankoshlyak commented on 9vKqVkMQHKk.sbv
> +0:12:25.100,0:12:25.600
видалити пуст

2020-07-17 19:02 UTC, romankoshlyak commented on 9vKqVkMQHKk.sbv
> +Тож те, що залишилося, - це гарне чисте 3(2х2).
3*2^2

2020-07-17 19:02 UTC, romankoshlyak commented on 9vKqVkMQHKk.sbv
> +3 * 2*2, або 12.
3*2^2

2020-07-17 19:02 UTC, romankoshlyak commented on 9vKqVkMQHKk.sbv
> +похідна t*3 як функція t = 3 х t*2.
t^3 3*t^2

2020-07-17 19:02 UTC, romankoshlyak commented on 9vKqVkMQHKk.sbv
>  0:13:08.660,0:13:12.139
видалити пумтий субтитр

2020-07-17 19:02 UTC, romankoshlyak commented on 9vKqVkMQHKk.sbv
> +І все-таки ми закінчили таким простим виразом: 3*t*2.
3*t^2

2020-07-17 19:02 UTC, romankoshlyak commented on 9vKqVkMQHKk.sbv
> +Знати, що похідна t3 дорівнює 3t2 - це одна з тих речей, які усі студенти-математики навчаються
t^3 3*t^2

2020-07-17 19:02 UTC, romankoshlyak commented on 9vKqVkMQHKk.sbv
> +0:14:05.280,0:14:05.780
delete

2020-07-17 19:02 UTC, romankoshlyak commented on 9vKqVkMQHKk.sbv
> +Подумайте про справжній автомобіль, який рухається відповідно до цієї функції відстані t3,
t^3

2020-07-17 19:02 UTC, romankoshlyak commented on 9vKqVkMQHKk.sbv
> +З одного боку, ми можемо обчислити його швидкість в цей момент, використовуючи похідну 3t2
3*t^2

2020-07-17 19:02 UTC, romankoshlyak commented on 9vKqVkMQHKk.sbv
> +0:15:06.540,0:15:07.040
delete

2020-07-24 17:40 UTC, OlZas commented on 9vKqVkMQHKk.sbv
> +Коли ви робите розрахунки в числівнику, ви отримуєте 23 + 3 * 22dt + 3 * 2 * (dt) 2
а не так - 2^3 + 3*2^2*dt + 3*2*dt^2 + dt^3 - 2^3 ?

2020-07-25 19:21 UTC, merged